<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWn6MUfq\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWn6MUfq/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWn6MUfq.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWn6MUfq\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWn6MUfq\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Wn6MUfq',
    'container.build_id' => 'e29d42cc',
    'container.build_time' => 1627303278,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWn6MUfq');
